name: Actions Workflow

on: 
  # push:
    # branches:
    #  - master
    #  - 'feature/*' # matches feature/featureA, feature/featureB
    #  - 'feature/**' # matches feature/feat/a
    #  - '!feature/featC' # ignore feature/featC
    # tags:
    #  - "v1.*"
    # paths:
    #  - '**.js' # only run if a js file was push
    # paths-ignore:
    #  - 'docs/**'
    # branches-ignore:
    #  - ""
  # schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  # repository_dispatch:
  #  types: [build]
  pull_request:
    types: [closed, assigned, opened, reopened]
  #  branchs:
  #    - master

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Payload
      #  run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: | 
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Flavio
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"